### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by productdevbook** [innovaccer/mobile-design-system#11]
Thanks for sharing this project. I hope it develops further.

**Comment by akshatsharma-innovaccer** [comment]
Stay tuned!!

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/158553042-78b22bbb-99f2-4b71-ab28-5da7ddb54c5f.png)

Thats true ? 

![image](https://user-images.githubusercontent.com/38668796/158553079-392a5ac3-e61e-49ce-a08b-3f5f27dfd2cd.png)

**Comment by hiashutoshsingh** [comment]
Hey, @productdevbook thanks for raising the issue.
Could you please elaborate what's the issue exactly?

Thanks

**Comment by productdevbook** [comment]
@hiashutoshsingh iam add button error `app null check operator used on a null value` library mds

**Comment by akshatkaneria** [comment]
Hey, @productdevbook we have published a new version (0.0.2), please try again with the new version.

Thanks.

**Comment by productdevbook** [comment]
@akshatkaneria dont fixed

![image](https://user-images.githubusercontent.com/38668796/160984595-e6b68033-b0b4-439c-8c50-25e87cf868b6.png)

**Comment by productdevbook** [comment]
@akshatkaneria thank you fixed
