### ISSUE TITLE
p3 how to used ?

### ISSUE THREAD

**Issue by productdevbook** [innovaccer/mobile-design-system#12]
https://github.com/innovaccer/mobile-design-system/blob/0239d5e46507c2a32af8f4cd07b3addc0d931a0c/example/lib/screens/home_screen.dart#L24

![image](https://user-images.githubusercontent.com/38668796/158597932-1a58e2b9-25fb-43bf-b4d4-cc69c8165b37.png)

iam add but working

**Comment by hiashutoshsingh** [comment]
Hey @productdevbook 
Please extend `SpacingMixin and ColorMixin` within your widget to use all theme-related properties such as p3(padding).
