### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by productdevbook** [innovaccer/mobile-design-system#13]
Will you create a documentation about how we should use it?

**Comment by hiashutoshsingh** [comment]
Hey @productdevbook 
Yes, our team is working on it. It's just our first step of making our design-system public. In the coming days, we will be adding documentation for every widget.

For now, you can refer to the example app.
https://github.com/innovaccer/mobile-design-system/tree/master/example/lib

**Comment by yash-ahir** [comment]
Hey, any update on the documentation?
